architecture: standalone

tls:
  enabled: true
  existingSecret: mongodb-ca-secret
  extraDnsNames:
  - "$app_server_addr"
auth:
  enabled: true
  rootUser: $mongo_root_username
  rootPassword: $mongo_root_password
persistence:
  enabled: true
  existingClaim: mongodb-pvc
securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

volumePermissions:
  enabled: true